spring:
  application:
    name: order
  rabbitmq:
    username: guest
    password: guest
    connection-timeout: 15000
    port: 5672
    host: 192.168.92.133
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/ls?useUnicode=true&characterEncoding=utf-8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 500
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: CONFIG
#      profile: test
#    stream:
#      bindings:
#        myMessage:
#          group: order
#          content-type: application/json
#  zipkin:
#    base-url: http://zipkin:9411/
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.openfeign: debug
server:
  port: 7777
env:
  dev
