spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/ls?useUnicode=true&characterEncoding=utf-8
  rabbitmq:
    username: guest
    password: guest
    connection-timeout: 15000
    port: 5672
    host: 192.168.92.133
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 500

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.netflix.feign: debug

env:
  dev
